version: '3'

services:
  minio:
    image: minio/minio:latest
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    command: ["server", "/data", "--console-address", ":9001"]

  db:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: server
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: astral
    volumes:
      - ./build/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh

  server:
    build: .
    depends_on:
      - db
      - minio
    ports:
      - 8080:8080
    entrypoint: server
    environment:
      POSTGRES_URL: "postgres://server:12345@db:5432/astral?sslmode=disable"
      MINIO_URL: "http://minioadmin:minioadmin@minio:9000"
